---
name: release
on:
  workflow_dispatch:
    inputs:
      publish_to:
        description: 'Where to publish the release to'
        required: true
        default: '"DockerHub", "GHCR", "GitHub"'
        type: string

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read   # needed for checkout
      packages: write  # needed for GITHUB_TOKEN to push to ghcr.io
    steps:
      # Step 1: Generate a short-lived token from the GitHub App
      - name: generate-app-token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.BROWNSERVE_CI_APP_ID }}
          private-key: ${{ secrets.BROWNSERVE_CI_APP_PRIVATE_KEY }}
      # Step 2: Checkout the repo
      - name: checkout-repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          path: ScoresOnTheDoors
      # Step 3: Run the build script
      - name: run-build-script
        shell: pwsh
        env:
          GitHubToken: ${{ steps.app-token.outputs.token }}
          GHCRToken: ${{ secrets.GITHUB_TOKEN }}
          DockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          DockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
            $Params = @{
              BranchName = $env:GITHUB_REF
              GitHubRepoName = 'ScoresOnTheDoors'
              Build = 'Release'
              GitHubReleaseToken = $env:GitHubToken
              GHCRToken = $env:GHCRToken
              DockerHubUsername = $env:DockerHubUsername
              DockerHubToken = $env:DockerHubToken
              PublishTo = ${{ inputs.publish_to }}
              Verbose = $true
            }
            ./ScoresOnTheDoors/.build/build.ps1 @Params
      # Step 4: Push a notification to Slack
      - name: notify-slack
        shell: pwsh
        if: ${{ always() }}
        env:
          BUILD_NOTIFICATION_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_BUILD }}
          BUILD_BRANCH: ${{ github.ref }}
        run: |
            ./ScoresOnTheDoors/.build/_init.ps1
            Send-BuildNotification `
              -BuildName ${{ github.job }} `
              -BuildStatus ${{ job.status }} `
              -Webhook $env:BUILD_NOTIFICATION_WEBHOOK `
              -RepoBranch $env:BUILD_BRANCH `
              -RepoName $global:BrownserveRepoName
